groups:
    - developer
    - smartie
recipes:
    global:
    mac_os_x:
        - applications::7zip
        - applications::cyberduck
        - applications::google-hangouts
        - applications::iterm2
        - applications::rdio
        - applications::virtualbox
        - applications::1password
        - applications::dropbox
        - applications::evernote
        - applications::istatmenus4
        - applications::omnigraffle
        - applications::things
        - applications::vlc
        - applications::alfred
        - applications::cord
        - applications::bartender
        - applications::mou
        - applications::flash
        - applications::spectacle
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::dock_do_not_animate_opening_applications_from_the_dock
        - osxdefaults::dock_enable_spring_loading_for_all_dock_items
        - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
        - osxdefaults::dock_minimize_to_application
        - osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::dock_position_the_dock_on_the_left_side
        - osxdefaults::dock_enable_highlight_hover_effect_for_the_grid_view_of_a_stack
        - osxdefaults::dock_remove_the_animation_when_hiding_showing_the_dock
        - osxdefaults::dock_remove_the_auto-hiding_dock_delay
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date
        - dotfiles::zsh
attributes:
    git:
        name: Luca Maraschi
        email: luca.maraschi@gmail.com
    osxdefaults:
        computername: Synapse
    dotfiles:
        kdeploy:
            hostname: dev
        vim:
            bundle:
                - gitgutter: git://github.com/airblade/vim-gitgutter.git
                - airline: https://github.com/bling/vim-airline
                - nerdtree: https://github.com/scrooloose/nerdtree.git
                - command-t: https://github.com/wincent/Command-T.git
                - fugitive: https://github.com/tpope/vim-fugitive.git
                - minibuffer: https://github.com/fholgado/minibufexpl.vim.git
                - tagbar: https://github.com/majutsushi/tagbar.git
                - simple-pairs: https://github.com/vim-scripts/simple-pairs.git
                - youcompleteme: https://github.com/Valloric/YouCompleteMe.git
